Update pr-check.yml

diff --git a/.github/workflows/pr-check.yml b/.github/workflows/pr-check.yml
--- a/.github/workflows/pr-check.yml
+++ b/.github/workflows/pr-check.yml
@@ -1,7 +1,7 @@
 name: PR Check
 
 on:
-  pull_request: ~
+  pull_request_target: ~
 
 jobs:
   check:
@@ -22,13 +22,13 @@ jobs:
           echo "==> PR Head is a fork: ${{ github.event.pull_request.head.repo.fork }}"
           echo "==> Changed files:"
           git diff --name-only HEAD^1 HEAD
-          echo "==> Violating files"
-          git diff --name-only HEAD^1 HEAD | grep '^\.github/' || echo "--None--"
           count=$(git diff --name-only HEAD^1 HEAD | grep -c '^\.github/') || count=0
           
           if [[ "${{ github.event.pull_request.head.repo.fork }}" = "true" && $count -gt 0 ]]; then
               echo "==> Found $count violations!"
-              echo "::error::Changed workflow in PR from fork!"
+              echo "==> Violating files"
+              git diff --name-only HEAD^1 HEAD | grep '^\.github/' || echo "--None--"
+              echo "::error::PR is trying to change a workflow!"
               exit 1
           fi
           echo "All OK"
