Update pr-check.yml

diff --git a/.github/workflows/pr-check.yml b/.github/workflows/pr-check.yml
--- a/.github/workflows/pr-check.yml
+++ b/.github/workflows/pr-check.yml
@@ -22,14 +22,15 @@ jobs:
           echo "==> PR Head is a fork: ${{ github.event.pull_request.head.repo.fork }}"
           echo "==> Changed files:"
           git diff --name-only HEAD^1 HEAD
-          echo "==> Violating files:"
-          git diff --name-only HEAD^1 HEAD | grep '^\.github/' || true
-          count=$(git diff --name-only HEAD^1 HEAD | grep -c '^\.github/')
+          echo "==> Violating files"
+          git diff --name-only HEAD^1 HEAD | grep '^\.github/' || echo "--None--"
+          count=$(git diff --name-only HEAD^1 HEAD | grep -c '^\.github/') || count=0
           
-          if [[ "${{ github.event.pull_request.head.repo.fork }}" = "true" && -n $count ]]; then
-            echo "==> Found $count violations!"
-            echo "::error::Changed workflow in PR from fork!"
-            exit 1
+          if [[ "${{ github.event.pull_request.head.repo.fork }}" = "true" && $count -gt 0 ]]; then
+              echo "==> Found $count violations!"
+              echo "::error::Changed workflow in PR from fork!"
+              exit 1
           fi
+          echo "All OK"
 
 
