Update pr-check.yml

diff --git a/.github/workflows/pr-check.yml b/.github/workflows/pr-check.yml
--- a/.github/workflows/pr-check.yml
+++ b/.github/workflows/pr-check.yml
@@ -17,18 +17,10 @@ jobs:
         with:
            fetch-depth: 2
       
-      - run: |
-          git rev-parse HEAD
-          git rev-parse HEAD^1
-      
-      - name: Get changes
-        run: git diff --name-only HEAD^1 HEAD
-
-      - if: ${{ github.event.pull_request.head.repo.fork }}
+      - name: Check .github dir
         run: |
-          echo "Changed workflow in PR from fork!"
-          exit 1
-      
-      - run: |
-          echo "All OK"
-          exit 0
+          count=$(git diff --name-only HEAD^1 HEAD | grep -c '^\.github/')
+          if [ "${{ github.event.pull_request.head.repo.fork }}" == "true" && $count -gt 0 ]; then
+            echo "::error::Changed workflow in PR from fork!"
+            exit 1
+          fi
